"""empty message

Revision ID: 5a255c9f0532
Revises: 
Create Date: 2020-04-25 23:41:29.308687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a255c9f0532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('businesses', sa.Column('cif', sa.String(length=40), nullable=False))
    op.add_column('businesses', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('businesses', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('businesses', sa.Column('phone', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'businesses', ['email'])
    op.create_unique_constraint(None, 'businesses', ['name'])
    op.create_unique_constraint(None, 'businesses', ['phone'])
    op.create_unique_constraint(None, 'businesses', ['cif'])
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'customers', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'phone')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.drop_column('businesses', 'phone')
    op.drop_column('businesses', 'name')
    op.drop_column('businesses', 'email')
    op.drop_column('businesses', 'cif')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###
